export const
    Data = {
    items: [
        {name: '测试', grade: '高一', subject: [{name: '地理', items: []}]},
        {name: '新架服务器测试', grade: '高三',
            subject: [{name: '数学', items: [{tizu_enname: 4, tizu_name: '17'}, {tizu_enname: 2, tizu_name: '9-16'}]}]
        },
        {name: '20190424高三二模', grade: '高三',
            subject: [{name: '地理', items: []},
                {name: '化学', items: []}, {name: '理数',
                    items: [{tizu_enname: 34, tizu_name: '[22][23]'}, {tizu_enname: 24, tizu_name: '17题子区域1'}, {tizu_enname: 26,
                        tizu_name: '18'}, {tizu_enname: 28, tizu_name: '19'}, {tizu_enname: 30, tizu_name: '20'}, {tizu_enname: 32,
                        tizu_name: '21'}, {tizu_enname: 22, tizu_name: '填空题'}]},
                {name: '理综', items: [{tizu_enname: 78,
                        tizu_name: '[33][34]'}, {tizu_enname: 80, tizu_name: '[35][36]'}, {tizu_enname: 82, tizu_name: '[37][38]'},
                        {tizu_enname: 56, tizu_name: '22'}, {tizu_enname: 58, tizu_name: '23'}, {tizu_enname: 60, tizu_name: '24'},
                        {tizu_enname: 62, tizu_name: '25'}, {tizu_enname: 64, tizu_name: '26'}, {tizu_enname: 66, tizu_name: '27'},
                        {tizu_enname: 68, tizu_name: '28'}, {tizu_enname: 70, tizu_name: '29'}, {tizu_enname: 72, tizu_name: '30'},
                        {tizu_enname: 74, tizu_name: '31'}, {tizu_enname: 76, tizu_name: '32'}]},
                {name: '历史', items: []},
                {name: '生物', items: []},
                {name: '文数', items: [{tizu_enname: 48, tizu_name: '[22][23]'}, {tizu_enname: 38,
                            tizu_name: '17题子区域1'}, {tizu_enname: 40, tizu_name: '18'}, {tizu_enname: 42, tizu_name: '19'},
                            {tizu_enname: 44, tizu_name: '20'}, {tizu_enname: 46, tizu_name: '21'}, {tizu_enname: 36, tizu_name: '填空题'}]},
                {name: '文综', items: [{tizu_enname: 116, tizu_name: '[43][44]'}, {tizu_enname: 118, tizu_name: '[45][46][47]'},
                            {tizu_enname: 84, tizu_name: '36-1'}, {tizu_enname: 86, tizu_name: '36-2题子区域1'}, {tizu_enname: 88,
                                tizu_name: '36-3'}, {tizu_enname: 90, tizu_name: '37-1'}, {tizu_enname: 92, tizu_name: '37-2'},
                            {tizu_enname: 94, tizu_name: '37-3题子区域1'}, {tizu_enname: 96, tizu_name: '38-1'}, {tizu_enname: 98,
                                tizu_name: '38-2'}, {tizu_enname: 100, tizu_name: '39'}, {tizu_enname: 102, tizu_name: '40-1'},
                            {tizu_enname: 104, tizu_name: '40-2'}, {tizu_enname: 106, tizu_name: '40-3'},
                            {tizu_enname: 108, tizu_name: '41-1'},
                            {tizu_enname: 110, tizu_name: '41-2'}, {tizu_enname: 112, tizu_name: '41-3'}, {tizu_enname: 114,
                                tizu_name: '42'}]},
                {name: '物理', items: []},
                {name: '英语', items: [{tizu_enname: 52, tizu_name: '改错'}, {tizu_enname: 50, tizu_name: '语法'},
                            {tizu_enname: 54, tizu_name: '作文'}]},
                {name: '语文', items: [{tizu_enname: 8, tizu_name: '13-1'},
                            {tizu_enname: 10, tizu_name: '13-2'}, {tizu_enname: 12, tizu_name: '15题子区域1'}, {tizu_enname: 14,
                                tizu_name: '16'}, {tizu_enname: 16, tizu_name: '20'}, {tizu_enname: 18, tizu_name: '21'}, {tizu_enname: 20,
                                tizu_name: '22题子区域2'}, {tizu_enname: 2, tizu_name: '6'}, {tizu_enname: 4, tizu_name: '8题子区域1'},
                            {tizu_enname: 6, tizu_name: '9'}]},
                {name: '政治', items: []}]
        }
        ]
};
